### ISSUE TITLE
how to use other python interpreters and modules?

### ISSUE THREAD

**Issue by ifmihai** [plotdevice/plotdevice#13]
I have to say first: Great project!
python needs something like this as hell, at least in my opinion

Now,
is it possible to use other python distribution?
I use anaconda python.
I read docs as much as i could (not much time)
but didn't find any clarifying answer.
Hence this issue.

I ask because i don't use system's python (i'm on mac, mavericks)
and i don't intend to anyway.

I've installed plotdevice as a module also, and apparently it works.
but I would love to play around in plotdevice app, but using anaconda's python and my libraries.

**Comment by ifmihai** [comment]
I tried the second variant, with sys.path.append()
But it throws exception:

```python
numpy.dtype has the wrong size, try recompiling
Traceback (most recent call last):
  File "<Untitled>", line 8, in <module>
    import pandas as P
  File "/Users/ifmichael/anaconda/lib/python2.7/site-packages/pandas/__init__.py", line 7, in <module>
    from . import hashtable, tslib, lib
  File "pandas/src/numpy.pxd", line 157, in init pandas.lib (pandas/lib.c:77926)
ValueError: numpy.dtype has the wrong size, try recompiling
```

**Comment by samizdatco** [comment]
Hmm, I bet it's seeing the system's copy of numpy rather than the one bundled with anaconda. Maybe try adding the site-packages directory to the front of the path rather than appending it to the tail?
```python
import sys
sys.path.insert(0, '/path/to/lib/python2.7/site-packages')
```

**Comment by ifmihai** [comment]
late post, but I tried this variant just now.
I wanted to say it works, which is great!
Thank you, now it's perfect :)

**Comment by ifmihai** [comment]
I succeded after reading http://plotdevice.io/tut/Libraries
1. in my plotdevice scripts folder
2. i created a new folder, pdutils
3.1. inside it, i created a __init__.py empty file
3.2. along with __init__.py, i created a pdutils.py (my library)
4. I tried to import it, it didn't work directly. I had to get there in terminal, open a python, and import it, to compile my library to be recognized as a module
5. then plotdevice recognized it.

Why didn't point 4 worked directly?

If we would have a setting in plotdevice.app, to use our own python installation, this all extra workaround will be avoided automatically => another +1 for python path setting.

**Comment by samizdatco** [comment]
As a result of embedding PyObjC in the module (ba23488d5ea64241552f36a18518cc2c6c5aea2b) and making some related changes to the build system, the PlotDevice app and module can both be built with homebrew interpreters (8298e6bc4b1db7db4f055815618e1eda82c37ab6). Just specify the python interpreter you want to use when running the `setup.py` script:

```bash
$ /usr/local/bin/python setup.py app # builds with homebrew python 2  
$ /usr/local/bin/python3 setup.py app # builds with homebrew python 3
```
