### ISSUE TITLE
Preferences do not open

### ISSUE THREAD

**Issue by rtalexander** [plotdevice/plotdevice#17]
Hi,

In running PlotDevice (PD), for some reason the Preferences panel will not open reliably. I've tried to access it via both the menu and keyboard short (cmd-,). It has opened a few times, but only after a long delay. And in those times that it did open, the list of type faces was unpopulated, and the list of sizes only had three items. Further, selecting a different font size had no effect on the text window.

![screen shot 2015-01-01 at 16 50 24](https://cloud.githubusercontent.com/assets/1168470/5593690/1183f792-91d7-11e4-847e-4a1977033454.png)

In the Console app, I noted that PD is not catching an exception that is thrown just after trying to open the preferences:

![screen shot 2015-01-01 at 16 48 57](https://cloud.githubusercontent.com/assets/1168470/5593693/3e88cac4-91d7-11e4-83f6-cb1e59520b50.png)

I'm running PD on a Mac Mini having the following configuration:

![screen shot 2015-01-01 at 17 00 28](https://cloud.githubusercontent.com/assets/1168470/5593701/b76bd328-91d7-11e4-91d0-d0f1fac19f3f.png)

Just for grins, I installed PD on another Mac Mini and the preferences seemed to work just fine. The configuration of that Mini is:

![screen shot 2015-01-01 at 17 04 59](https://cloud.githubusercontent.com/assets/1168470/5593713/6e8e17d2-91d8-11e4-8777-58dde9522234.png)

Any ideas or suggestions?

Thanks,

Roger Alexander.

**Comment by rtalexander** [comment]
Hi,

I just tried PD on my MBP and have observed the same behavior as the first Mac Mini. The configuration of the MBP is:

![screen shot 2015-01-01 at 9 30 27 pm](https://cloud.githubusercontent.com/assets/1168470/5594524/3ad6b43a-9205-11e4-85f8-fa875f7ec7f3.png)

Roger Alexander.

**Comment by samizdatco** [comment]
Hi roger, this is a known issue with version 0.9.4 on systems where the user's home directory is not at `/Users/<username>`. To the best of my knowledge this has been fixed (see #7) and the changes will be included in the 0.9.5 release that should be posted Real Soon Now...

Are you running into this bug when building the app from current sources or only with the precompiled app on plotdevice.io?

**Comment by rtalexander** [comment]
Hi Christian, 

Thanks for the reply. You hit the nail on the head. Both of the computers that have the problem have my user directory on a different volume (though there it is symlink’d). My user folder is in the usual place on the computer on which PD worked. I was using the precompiled app.

On an unrelated note, is there a discussion forum for PD? I have some general questions that I would like to ask that are not problem-related.

Thanks,

Roger.
