### ISSUE TITLE
CENTERX and CENTERY dynamic variables?

### ISSUE THREAD

**Issue by ifmihai** [plotdevice/plotdevice#18]
from my little experience, I see there are 2 modes of thinking and plotting.
1. chart like, xy, cartesian.
2. polar charts.

Doing both, I saw I need center coordinates, especially in polar plotting, obviously.

I was wondering: why wouldn't they be defined as dynamic variables? they are forever useful (at least in my case :) )

**Comment by samizdatco** [comment]
i've got some ideas for object-grouping and relative coordinate frames that should pop up in the 0.9.6 timeframe. meantime, take a look at the Point object (and its [trig methods](http://plotdevice.io/tut/Geometry#Point-Geometry) in particular) for help with these sorts of polar calculations.
