### ISSUE TITLE
docs: issue with random()

### ISSUE THREAD

**Issue by ifmihai** [plotdevice/plotdevice#19]
it's a little confusion about random()

First, docs say 
```choice(sequence)``` is like ```sequence[random(len(sequence)]```
suggesting that random(5) gives something between 0 and 4

but afterwards it says otherwise:
```r = random(5) # returns an int between 0 and 5```
suggesting that random() can return right side of the interval also (5 in this case)

which is it?
because it seems, from practice, that first example is actually real

**Comment by samizdatco** [comment]
it's the former: the range is from 0 to *n* non-inclusive. take a look at `help(random)` in the repl
