### ISSUE TITLE
variables issue when animating

### ISSUE THREAD

**Issue by ifmihai** [plotdevice/plotdevice#20]
I am not able to pinpoint the cause to this.

Some variables declared outside draw() animating function, 
are not being recognized when used inside draw() function

```python
S = 0

def draw():
   # bla bla bla
   S += 1
```

throws exception:
```python
Traceback (most recent call last):
  File "random_counter.pv", line 76, in draw
    S += 1
UnboundLocalError: local variable 'S' referenced before assignment
```

What's puzzling, this does not happen to all variables. I have some variables declared outside draw(), and they work as expected.

Is this a bug? or am i missing something obvious?

ps.
if I do
```python
def draw():
    global S
    # bla bla bla
    S += 1
```
then it works

**Comment by samizdatco** [comment]
yep, that's how variable scope works in Python
