### ISSUE TITLE
animation, var() and draw()

### ISSUE THREAD

**Issue by ifmihai** [plotdevice/plotdevice#21]
I declared a variable with var()

``` python

var("topn", NUMBER, 5, 1, 10)

def draw():
    s = '1' * topn
    text(s, 50, 50)
```

but it seems only the default value is used, so even if i change topn with mouse, nothing happens.
Is this ok? or s should be updated accordingly?

**Comment by samizdatco** [comment]
This should now work, though you'll want to change your code to make sure the variable is an integer before using it to multiply characters:
```python
var("topn", NUMBER, 5, 1, 10, step=1)

def draw():
    s = '1' * int(topn)
    text(s, 50, 50)
```

fixed in a391cef3425e4618b220f22e2a7dcd8660e0678e
