### ISSUE TITLE
[feature request] possibility to load last open file(s) by default

### ISSUE THREAD

**Issue by ifmihai** [plotdevice/plotdevice#23]
each time i open plot device, i close the default new script usually, and open one of my last scripts.

it's not a big deal after all, to close the new default script, and load recent files

but because of memory bug #22 
i have to close plotdevice and open it back, many times

**Comment by samizdatco** [comment]
try not closing your script windows before quitting and relaunching. os x's auto-resume feature will re-open them for you.
