### ISSUE TITLE
Path to current script

### ISSUE THREAD

**Issue by mrpalacz** [plotdevice/plotdevice#27]
I'm migrating my projects vom NodeBox to PlotDevice, one problem I encountered is that I can't seem to get a path to the .pv file like I did with NodeBox for the .py file.
The variable `__file__` also didn't work in NodeBox, but `sys.argv[0]` did work in NodeBox once the file was saved. In PlotDevice I only get `<untitled>` when printing the var.

**Comment by mrpalacz** [comment]
`sys.argv[0]` works fine when the file is closed and opened again.

**Comment by samizdatco** [comment]
Actually, this seems like a good thing to add. Let me look into it...

**Comment by mrpalacz** [comment]
:+1:
