### ISSUE TITLE
coreimage.gfx.transform doesn't exist

### ISSUE THREAD

**Issue by towerofnix** [plotdevice/plotdevice#29]
Here's my code:

``` python
coreimage = ximport("coreimage")
canv = coreimage.canvas(150, 150)
```

And here's the error output:

```
Traceback (most recent call last):
  File "FirstCoreImage.pv", line 8, in <module>
    canv = coreimage.canvas(150, 150)
  File "coreimage/__init__.py", line 577, in canvas
    from plotdevice.gfx.transform import Dimension
ImportError: No module named transform
```

As you can see `plotdevice.gfx.transform` isn't an existing module.

Mac OS X 10.10.5. Using plotdevice 0.10 (r964).

Help?

**Comment by PodrugStudio** [comment]
I have same problem. Any luck solving it ?

**Comment by liam4** [comment]
The code for `ximport` follows:

```python

**Comment by liam4** [comment]
AHA!

https://github.com/plotdevice/plotdevice/commit/bdaa32bc086deb2dc2cf827b9236f526b1639583

"Renamed gfx.transform to gfx.geometry"

I can't test it now but maybe if you change line 577 of coreimage/__init__ you can fix it?

```diff
-    from plotdevice.gfx.transform import Dimension
+    from plotdevice.gfx.geometry import Dimension
```

**Comment by PodrugStudio** [comment]
Yes that helped!

I got brand new error now but will search about it :)
(canvas = coreimage.canvas(320, 240)
AttributeError: 'module' object has no attribute 'canvas')

Thank you!

**Comment by liam4** [comment]
Well, that's strange..

Your program probably does this:

```python
coreimage = ximport('coreimage')
```

`ximport` basically does this:

```python
lib = __import__('coreimage')
# do some stuff
return lib
```

Inside of `coreimage/__init__.py`, on line 576, `canvas` is defined:

```python
def canvas(w=None, h=None, renderer=None, quality=None):
```

There's no `__all__` set so it should be available from importing `coreimage`.

So the `coreimage` object *should* have a `canvas` attribute.. hmm..

**Comment by PodrugStudio** [comment]
Yes I saw it there too, but being new with python, don't know exactly where to look further as seems like nobody else have this problem :)

**Comment by liam4** [comment]
That's great! Glad I could help. :)

Closing as it's not an issue with PlotDevice, it's a problem with Core Image.

Though it might be nice if there was an alias made, i.e. gfx.transform -> gfx.geometry...

**Comment by liam4** [comment]
Mm, reopening because Core Image *is* part of PlotDevice. :)

**Comment by oshabal** [comment]
After doing 
-    from plotdevice.gfx.transform import Dimension
+    from plotdevice.gfx.geometry import Dimension

Now I'm getting
`Traceback (most recent call last):
  File "sandbox.pv", line 5, in <module>
    p = l.pixels()
  File "../Library/Application Support/PlotDevice/coreimage/__init__.py", line 1197, in pixels
    return self.canvas.renderer.pixels(self)
  File "../Library/Application Support/PlotDevice/coreimage/__init__.py", line 1632, in pixels
    img = self.render(layer, crop=crop)
  File "../Library/Application Support/PlotDevice/coreimage/__init__.py", line 2411, in render
    img = self.render_opacity(layer, img)
  File "../Library/Application Support/PlotDevice/coreimage/__init__.py", line 2362, in render_opacity
    "inputBackgroundImage" : self.image(LAYER_FILL, Transparent(), w, h, x=x, y=y),
  File "../Library/Application Support/PlotDevice/coreimage/__init__.py", line 1503, in image
    a.setImage_(img)
AttributeError: 'NoneType' object has no attribute 'setImage_'`

**Comment by samizdatco** [comment]
CoreImage is now *running*, but not terribly well. If you can figure out where some of its misbehaviors are coming from, I'd love to hear about it: https://github.com/plotdevice/plotdevice-libs/tree/master/coreimage
