### ISSUE TITLE
suggestion: CLI export with default filename, batch export

### ISSUE THREAD

**Issue by dimitre** [plotdevice/plotdevice#32]
It would be great to be able to use CLI to export with default filename (same name of .py file with .pdf extension). something like:

```
plotdevice test001.py --export pdf
```

Other great feature would be able to export multiple files at the same time, like:

```
plotdevice *.py --export pdf
```

Thank you!

**Comment by samizdatco** [comment]
Using the script file's name as a default is a nice suggestion. The batch processing in your second example seems like it might be better handled with shell scripting though. That way you could even run the different scripts in parallel with something like:
```sh
for f in *.py; do 
    plotdevice "$f" --export "${f%.py}.pdf" &
done
```
