### ISSUE TITLE
CMYK values are not preserved

### ISSUE THREAD

**Issue by dreerr** [plotdevice/plotdevice#37]
CMYK values are not preserved when creating a PDF. For example the following code:

```
colormode(CMYK)
outputmode(CMYK)
fill(CMYK,0,0,0,1.0)
rect(10,10,100,100)
```

exported with option _Convert to CMYK_ activated results in a CMYK PDF but with the color
![bildschirmfoto 2015-11-16 um 11 15 13](https://cloud.githubusercontent.com/assets/1454661/11179415/5ae48ace-8c53-11e5-8ffc-cb50fa27cb36.png)

I already tried variations of colormode and outputmode, but the goal of a pure CMYK black (0/0/0/100) is never reached.

Version 0.10.0 (r964)

**Comment by dimitre** [comment]
+1
