### ISSUE TITLE
Building the module requires Xcode

### ISSUE THREAD

**Issue by sctice** [plotdevice/plotdevice#46]
Due to [these two lines][1] in the `BuildCommand` class, building the module requires a full Xcode install. I have a developer tools install but no need for Xcode itself. It would be very nice to have an option to build the module so that it can be used for non-interactive drawing applications without requiring Xcode.

I manually removed the lines and went through a build and install without issues. I'm sure that there are components I can't use (though I haven't come across them yet), so it would probably be a good idea to enable building with or without `ibtool` based either on some flag or just on `ibtool` being available (maybe with a warning message if it isn't).

[1]: https://github.com/plotdevice/plotdevice/blob/master/setup.py#L217-L218

**Comment by samizdatco** [comment]
the `sdist` created for pip installs now includes a precompiled viewer.nib file so it should only require the xcode command line tools: 147f61c1537bfd48586bfee5c0d31c6996d90ad3
